[package]
name = "levenberg-marquardt"
version = "0.4.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Levenberg-Marquardt algorithm built on top of nalgebra"
keywords = ["estimation", "estimator", "levenberg", "marquardt"]
categories = ["algorithms", "computer-vision", "science::robotics", "no-std", "mathematics"]
repository = "https://github.com/rust-cv/levenberg-marquardt"
documentation = "https://docs.rs/levenberg-marquardt/"
license = "MIT"
readme = "README.md"

[dependencies]
nalgebra = { version = "0.20.0", default-features = false }
alga = { version = "0.9.3", default-features = false }
num-traits = { version = "0.2.11", default-features = false }

[dev-dependencies]
arrsac = "0.3.0"
rand = { version = "0.7.3", default-features = false }
nalgebra = "0.20.0"
pcg_rand = "0.11.1"
sample-consensus = "0.2.0"

[profile.test]
# This is necessary so we can test as many estimations as possible.
opt-level = 3

[package.metadata.docs.rs]
# To build locally use
#   RUSTDOCFLAGS="--html-in-header katex-header.html" cargo doc --no-deps
rustdoc-args = [ "--html-in-header", "katex-header.html" ]